### ISSUE TITLE
mod_chrome_v102 failed - no such table: urls

### ISSUE THREAD

**Issue by dclendening** [CrowdStrike/automactc#4]
automactc: 
ERROR
mod_chrome_v102 failed:
 ['Traceback (most recent call last):\n  File "../automactc.py", line 351, in modExec\n    import_module(modImport)\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module\n    __import__(name)\n  File "/Users/dclendening/Desktop/automactc-master/modules/mod_chrome_v102.py", line 298, in <module>\n    module(chrome_location)\n  File "/Users/dclendening/Desktop/automactc-master/modules/mod_chrome_v102.py", line 282, in module\n    pull_visit_history(history_db, user, profile, urls_output, urls_headers)\n  File "/Users/dclendening/Desktop/automactc-master/modules/mod_chrome_v102.py", line 114, in pull_visit_history\n    u_cnames = get_column_headers(history_db, \'urls\')\n  File "/Users/dclendening/Desktop/automactc-master/modules/mod_chrome_v102.py", line 53, in get_column_headers\n    **col_headers = sqlite3.connect(db).cursor().execute(\'SELECT * from {0}\'.format(column))\nOperationalError: no such table: urls**\n']

**Comment by dclendening** [comment]
Ran with:
`automactc.py -m all -fmt json`

**Comment by kshitijkumar14** [comment]
Fixed error handling to skip and move on if a table is missing from a database in module version 1.0.4. Error likely has to do with a table simply being absent from the db in question... would be curious to know what chrome version/history db version was reported (should be a debug message in runtime.log).
